### ISSUE TITLE
Flickraw reporting an error on generate for thumbnails of a set

### ISSUE THREAD

**Issue by rgarner** [neilk/octopress-flickr#10]
Having set up according to instructions, and on using a `{% flickr_set 12345678 t %}` tag (note: this only applies to thumbnails), I get  

```
Liquid Exception: undefined method `owner' for 
#<FlickRaw::Response:0x000001030ef660> in index.markdown
```

It looks like `flickr.rb:543` is trying to use the photo as a response and `Flickraw` expects an `#owner` on it which isn't there.

```
Building site: source -> public
Liquid Exception: undefined method `owner' for #<FlickRaw::Response:0x000001030ef660> in index.markdown
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/flickraw-0.9.6/lib/flickraw/api.rb:192:in `url_photostream'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/flickraw-0.9.6/lib/flickraw/api.rb:179:in `url_photopage'
/Users/russ/some-user/some-project/plugins/flickr.rb:543:in `block in getHtml'
/Users/russ/some-user/some-project/plugins/flickr.rb:533:in `each'
/Users/russ/some-user/some-project/plugins/flickr.rb:533:in `getHtml'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/persistent_memoize-0.0.1/lib/persistent_memoize.rb:18:in `block in memoize'
/Users/russ/some-user/some-project/plugins/flickr.rb:512:in `render'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/liquid-2.3.0/lib/liquid/block.rb:94:in `block in render_all'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/liquid-2.3.0/lib/liquid/block.rb:92:in `collect'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/liquid-2.3.0/lib/liquid/block.rb:92:in `render_all'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/liquid-2.3.0/lib/liquid/block.rb:82:in `render'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/liquid-2.3.0/lib/liquid/template.rb:124:in `render'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/liquid-2.3.0/lib/liquid/template.rb:132:in `render!'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-0.12.0/lib/jekyll/convertible.rb:79:in `do_layout'
/Users/russ/some-user/some-project/plugins/post_filters.rb:167:in `do_layout'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-0.12.0/lib/jekyll/page.rb:100:in `render'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-0.12.0/lib/jekyll/site.rb:204:in `block in render'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-0.12.0/lib/jekyll/site.rb:203:in `each'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-0.12.0/lib/jekyll/site.rb:203:in `render'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-0.12.0/lib/jekyll/site.rb:41:in `process'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-0.12.0/bin/jekyll:264:in `<top (required)>'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/bin/jekyll:23:in `load'
/Users/russ/.rvm/gems/ruby-2.0.0-p247/bin/jekyll:23:in `<main>'
Build Failed
```

**Comment by neilk** [comment]
I originally thought your problem was a syntax error (using `flickr set` rather than `flickr_set`), but the error is different. So I assume you just mistyped things in your bug report. 

That said, I can't replicate your problem. I've tried a set which I know exists, and I also tried `12345678` in case a non-existent set causes the issue, but this either works fine or generates an appropriate error message.

Please supply more information so I can replicate the problem. What is the markup that is failing, exactly?

**Comment by rgarner** [comment]
You're quite right, I mistyped the original - sorry about that. I've corrected it now. I've just tried on a fresh rvm install on a different machine of ruby 2.0.0-p247. Bundle install locks flickraw at 0.9.6 (full [Gemfile.lock](https://gist.github.com/rgarner/7020258)), stack trace is identical.

Failing markdown is:

```
---
layout: page
title: "gallery"
date: 2013-10-13 07:44
comments: true
sharing: true
footer: true
---

{% flickr_set 72157636613600394 %}
```

I can work around this (since `response` does have an owner) by changing `flickr.rb:543` from:

``` ruby
        "page_url" => FlickRaw.url_photopage(photo) + photo.id,
```

to

``` ruby
        "page_url" => FlickRaw.url_photostream(response) + photo.id,
```

**Comment by neilk** [comment]
Okay, I can replicate it, but I don't see what's special about this set that causes the problem. It looks the same as every other API reponse.

Also, in your fix you make it so that the link to the original image's photo page now just goes to the user's photostream. This is not desired behavior. 

Are you sure this is a bug with octopress-flickr? It seems like a bug with the underlying FlickRaw library, although I don't understand it yet.

**Comment by rgarner** [comment]
OK, so it happens with this set but not with others? I'll check and see if there was any special property I set when creating it.

No, I'm not sure it's a problem with octopress-flickr now. My fix seems to work - the links seem to go to the actual photos due to the `+ photo.id`id` - working gallery [here](http://redhallplayingfields.org.uk/gallery). I just wondered if octopress-flickr was dependent on an older version of FlickRaw. I can't confess to totally understand it either - this is my first exposure to Flickr's API ever.

**Comment by neilk** [comment]
Aha, now I see what's different. The photos in the failing set have a 'pathalias' of nil, and no 'owner'. Then we try to construct the URL simply from the photo, and it fails.

Seems like this should be a bug in the Flickr API - maybe recent api changes have caused this.

**Comment by rgarner** [comment]
Hmm, maybe I should try recreating the set to see if it was a transient creation issue on Flickr.

**Comment by neilk** [comment]
No, I double checked - it's not a bug in the Flickr API. It's kind of weird that the Flickr API even offers pathalias info in the photo record to begin with, since it's a property of the user.
