### ISSUE TITLE
Octopress-flickr only looks 'correct' with 'classic' theme

### ISSUE THREAD

**Issue by billchilders** [neilk/octopress-flickr#4]
It seems that octopress-flickr only generates its HTML correctly with the 'classic' theme that ships with octopress. The plugin does work with other themes (I'm using 'darkstripes' from here: https://github.com/amelandri/darkstripes), but the captions and labeling appear in the wrong font and just look clunky and incorrect.

I've taken a stab at unravelling why, but so far it eludes me. Have you seen this?

Thanks!
- Bill

**Comment by neilk** [comment]
The problem is that darkstripes overwrites `sass/screen.scss`; it should have the following line at the end:

```
@import "plugins/**/*";
```

Add that line and it should work. Thanks for the bug - I updated the instructions.
