### ISSUE TITLE
missing shadow-box mixin

### ISSUE THREAD

**Issue by dfalster** [neilk/octopress-flickr#5]
this looks like a great plugin. tried to install on my octopress site, following your instructions, and got the following error. Any ideas?

Syntax error: Undefined mixin 'shadow-box'.
        on line 28 of /Users/dfalster/Dropbox/Documents/dfalster.github.io/sass/plugins/_flickr.scss, in `shadow-box'
        from line 28 of /Users/dfalster/Dropbox/Documents/dfalster.github.io/sass/plugins/_flickr.scss
        from line 5 of /Users/dfalster/Dropbox/Documents/dfalster.github.io/sass/screen.scss

**Comment by neilk** [comment]
shadow-box is a SASS mixin which is bundled with the standard Octopress theme in [sass/base/_utilities.scss](https://github.com/imathis/octopress/blob/master/.themes/classic/sass/base/_utilities.scss). If your theme doesn't have it, copy the appropriate block from that file. If you really started your theme from scratch, maybe you'll also need its dependencies, but I think you know what to do now.
