### ISSUE TITLE
Allow specifying private Flickr info in _config.yml

### ISSUE THREAD

**Issue by duckpuppy** [neilk/octopress-flickr#6]
I understand using environment variables for safety, but it would be nice if we could also specify the Flickr shared secret and api key in the _config.yml file.  I keep the code for my blog in a private repo, so I don't mind storing that info in there rather than configuring the same environment variables in multiple places.

**Comment by neilk** [comment]
fixed in 315765551fbacc1e63e6b7cd78fde091fd855f39
